apiVersion: apps/v1
kind: Deployment
metadata:
  name: jservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jservice
  template:
    metadata:
      labels:
        app: jservice
    spec:
      containers:
      - name: jservice
        image: neelinihal/jservice:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

